### PR TITLE
New exp_safe_html transform

### PR DESCRIPTION
**Pull request by prakharjoshi**
This is a new pull request for transform because in the old pull request for transform the travis failed and I can't find to fix that up :(

### CODE REVIEW

**Comment by prakharjoshi** [comment]
Seems like travis failed due to setuptools. Tests are passing in local and new transforms have been registered. Don't know why travis is sad here ?

**Comment by gforcada** [comment]
@prakharjoshi on the first two commits travis tests passed, on the third they started to fail, the easiest you can do is split that commit into smaller ones to help diagnose what's going wrong on that commit.

You can emulate travis locally as well, just follow what .travis.yml is doing on a new environment every time...

**Comment by prakharjoshi** [comment]
@gforcada  I tried to run travis locally and here is the error log http://pastebin.com/6XaN6mhN .  But there is an extra folder for buildut-cache has been created and two sub folders eggs and downloads have also been created but then it shows this error. Is there some change in buildouts (versions) ?

**Comment by lentinj** [comment]
@prakharjoshi You're right to suspect that there's been a change in the travis buildout config. I'm not sure precisely what is going wrong here.

However, you should be at least able to run the tests locally using the normal `buildout.cfg` for now.

**Comment by prakharjoshi** [comment]
@lentinj  Yeah normally local tests are running properly and the zope instance is running properly. I guess this is buildout error as it fails in travis and working properly in local. I tried to do it locally what travis does on every new commit(followng .travis.yml) and seems like that also fails in local.

**Comment by prakharjoshi** [comment]
@lentinj  @tisto  I am closing this pull request as I created a new one #28

**Pull request closed without merging**
