### PR TITLE
new branch for issue#42

### PR DESCRIPTION
**Pull request by prakharjoshi**

### CODE REVIEW

**Comment by prakharjoshi** [comment]
Finally!!!! @tisto  @lentinj  @gforcada  Finally a correct pull request is generated. Have a look at it and I guess we can merge it now. I will close the other stale pull requests. I just changed the versions from 4.3.3 to 5.0 and things worked perfectly :)

**Comment by lentinj** [comment]
Looks good to me. You should be able to get `test_add_new_link()` working if you fix the URL in the test, something like "http://nohost/plone/++add++Document" should work.

**Comment by prakharjoshi** [comment]
@lentinj  Ah!! that link "http://nohost/Plone/++add++Document" :( . I guess this is because we have used Plone-4 for creating the add-on and now travis is testing on Plone-5, is that the reason for test failure ?

**Comment by lentinj** [comment]
Yes. In upgrading you've switched from Archetypes to Dexterity. They create new content in different ways, and generate different URLs. Try it on your own site to check.

**Comment by prakharjoshi** [comment]
Yeah when I tried to run the tests on my local with this url `http://nohost/plone/portal_factory/Document/document.2015-10-30.4475775406/edit` it worked but travis here checks with dexterity content so its failing here and also when I tried to test with the dexterity link as you provided earlier in my local tests are failing.

**Comment by gforcada** [comment]
@prakharjoshi then you need to run buildout so you get upated to plone 5 ;-)

**Comment by prakharjoshi** [comment]
@gforcada thanks :)

**Comment by prakharjoshi** [comment]
@lentinj @gforcada @tisto  I tired to write functional tests for the add new document form and here the test for the same

```
def test_add_new_link(self):
        self.browser.open("http://nohost/plone/++add++Document")
        self.assertTrue(
            'Add Page' in self.browser.contents)
```

But seems like this url is not found while running the tests and the log is like this http://pastebin.com/VAHr3Yex . I have also tried using this as a url `self.browser.open(self.portal.absolute_url() + "/++add++Document")` but still the result is same. Any idea ?

**Comment by gforcada** [comment]
@prakharjoshi if you start the instance (`bin/instance`) and type this URL it does work?

Another debug tip: put a pdb before your `browser.open` call and when on the test runner stops at the pdb type the following:

```
self.browser.open('http://nohost/plone')
open('/tmp/debug.thml', 'w').write(self.browser.contents)
```

Then open on your browser this URL `file:///tmp/debug.html` and see if that link (`++add++Document`) shows up somewhere.

**Comment by prakharjoshi** [comment]
@gforcada  Yeah the url `http://0.0.0.0:8080/plone/++add++Document` is working properly on the Plone instance and also in the tests this url is working `self.browser.open('http://nohost/plone')` . But I want to test this url `self.browser.open("http://nohost/plone/++add++Document")` and this has not been traced in the tests and not even in the pdb.

The commands you guided me were working perfectly but when I am trying to access `http://nohost/plone/++add++Document` instead of `http://nohost/plone` in pdb also it is showing site error.

**Comment by lentinj** [comment]
I suspect `plone.app.contenttypes` isn't installed in the instance that your unit tests create. So there isn't a Document content type registered to add.

There's various things you could do, but what I normally do is add it to `setUpZope` and `setUpPloneSite` in https://github.com/collective/experimental.safe_html_transform/blob/iss%2342/src/experimental/safe_html_transform/testing.py in the same way your own product is registered.

Ordinarily you would also to add it as a test dependency in https://github.com/collective/experimental.safe_html_transform/blob/master/setup.py but it looks like it's already there.

**Comment by gforcada** [comment]
@prakharjoshi I was expecting all of that, was just to confirm that there was nothing wrong already and as @lentinj pointed out you are missing p.a.contenttypes on you testing layer.

**Comment by tisto** [comment]
https://github.com/collective/experimental.safe_html_transform/pull/46 has been merged.

**Pull request closed without merging**
