### PR TITLE
setting up browser and just a simple sample test

### PR DESCRIPTION
**Pull request by prakharjoshi**
This is pull request where I just set the browser for functional tests and just included the basic functional tests, will include more tests in this :)

### CODE REVIEW

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  Have a look at this, tests are passing in local but here travis says that "its not an active repository" . Are there some updates on travis settings ? Or we have to change travis settings if we include functional tests ?

**Comment by tisto** [comment]
Travis is enabled now. You forgot to add the utf-8 encoding header in your file.

https://travis-ci.org/collective/experimental.safe_html_transform/builds/75342791

**Comment by prakharjoshi** [comment]
@tisto  Thanks :+1:

**Comment by prakharjoshi** [comment]
I have just upgraded my firefox and now it seems like the robot test is failing in my local enviornment, However travis is happy and before upgradation also the test case were passing but after upgradation the robot test is failing on local and the log says 

`Failure in test Scenario As a member I want to be able to log into the website (test_example.robot)
Traceback (most recent call last):
  File "/home/prakhar/projects/experimental.safe_html_transform/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/prakhar/projects/experimental.safe_html_transform/eggs/robotsuite-1.6.1-py2.7.egg/robotsuite/__init__.py", line 455, in runTest
    assert last_status == 'PASS', last_message
AssertionError: Setup failed:
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.
`

**Comment by prakharjoshi** [comment]
Okay here is the thing. We have our new transform (exp_safe_html)  and that is replacing the old transform (safe_html) now to check if tinyMCE is using our new transform. Here is what we can do is either 1) create the new transform with same name as previous 2) or create the new transform with different name.

earlier we did took the later approach and it was working fine until we have written test to check for tinyMCE, Now when I wrote tests then I realized that even tinyMCE calls for safe_html by getToolByName and here are the lines `Products.TinyMCE-1.3.9-py2.7.egg/Products/TinyMCE/utility.py", line 391, in getValidElements` and `Products.TinyMCE-1.3.9-py2.7.egg/Products/TinyMCE/utility.py", line 720, in getValidElements`  that calsl the transform name safe_html from portal_transforms and that we have deregistered just after add-on installation. 

So we have 2 options either we create the new transform with same name or we change the safe_html to exp_Safe_html in the tinyMCE in above mentioned lines and then things will work fine. Atleast in local things are working perfectly. 

I here in the pull request changed the transform name to safe_html from exp_safe_html , But in local I have experimented the other way also by changing safe_html to exp_Safe_html in tinyMCE utility.py(in the eggs) and that also worked perfectly.

Now I think we should change the transform name to safe_html, right now as if we change things in tinyMCE then errors will occur until do not install our new add-on. Here I have not seen the travis check.
Please have a look at this @tisto  @lentinj .

**Comment by miohtama** [comment]
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details. <-- It is an issue caused by Firefox update.

https://github.com/SeleniumHQ/selenium/issues/927

Downgrade to Firefox 40 to resolve the issue.

**Comment by prakharjoshi** [comment]
@miohtama  I checked the Firefox version and when I did `firefox -V` it shows `(process:24772): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Mozilla Firefox 40.0
`
So FireFox is of version 40 still I am having the same problem.

**Comment by lentinj** [comment]
@prakharjoshi Sorry, missed comment above about safe_html naming inamongst the Firefox debugging. Yes, you're spot on and made the right decision.

The tests I see in this pull request so far aren't robot tests though, although they are functional tests. Are the robot tests held up by getting your Firefox working?

**Comment by prakharjoshi** [comment]
@lentinj  Yeah these are functional tests yet as still I am getting same problem with firefox though I have downgraded firefox version to 39 :(

**Comment by tisto** [comment]
@prakharjoshi if the robot tests are causing troubles I'd be ok with just having functional zope.testbrowser tests for now. As long as the TinyMCE integration is not implemented I guess we don't need them anyways. To test the transform zope.testbrowser is enough, we don't need JS for that.

**Comment by prakharjoshi** [comment]
@tisto I guess the tinyMCE is using our new transform and not the old safe
html. I have one last functional test written for the same. Please have a
look at that.

**Comment by lentinj** [comment]
@prakharjoshi Which test are you referring to? None of the tests in this pull request look like they edit content.

**Comment by prakharjoshi** [comment]
@lentinj  Not editing content but I have the test that renders the url for new page and shows that page. It shows that the tinyMCE is getting the safe_html transform, the new one. If tinyMCE is not getting the safe_html transform then this page have shown the error.

**Comment by lentinj** [comment]
@prakharjoshi That doesn't show the transform being used though, just it managed to find one with the right name.

**Comment by prakharjoshi** [comment]
Okay so for that we have to add a document through functional test and
check the output as we have done in unit tests ?

**Comment by lentinj** [comment]
Yeah, so:-
- Add a page
- Find text field, add some HTML
- Save
- Check that the HTML on the resultant page has been filtered.

**Comment by prakharjoshi** [comment]
@lentinj  @tisto  Okay so I tried to add a new page with my add-on and I got the form to create a new page and then I filled the title and when I tired to select the test format for the Body text, it is only showing 2 options `Textile` and `Html` but the 3rd option with `Filter output Html` is not shown in the drop down list. So it seems like the tinyMCE is right now is not using the transform to filter Html so can hint how to fix that ?

**Pull request merged**
