### PR TITLE
Issue21

### PR DESCRIPTION
**Pull request by prakharjoshi**
@lentinj @tisto Here There Have to work on testing part again but this is the work I have done till now for safe_html part with the safe_html.py script in lxml and the test cases in tests/safe_html

### CODE REVIEW

**Comment by prakharjoshi** [comment]
Here I copy the things that have been discussed on the other issues.. Sorry for all the messup I am trying to clean it up as much as possible..

TISTO'S COMMENT :- 
@prakharjoshi FYI: you are importing and testing the datastream method from Products.PortalTransforms here. This has nothing to do with your safe_html transform. You are testing a method from another package which does not really makes sense. Have a look at plone.intelligenttext how the transform is tested there...

LENTINJ'S COMMENT :- 
@tisto datastream is part of the Transforms API, so importing it is pretty essential if you're testing that you are compliant with the API.

@prakharjoshi it's not a testing bug per-se. It's the only way to do it given the current structure of convert(), and you have to have at least some tests of this form to make sure you comply with the PortalTransforms API specification. The bigger problem is you're not compliant with this API. If we look at:-

https://github.com/plone/Products.PortalTransforms/blob/master/docs/dev_manual.rst

... it says that your convert() method should return a datastream object, and it doesn't currently.

Back to @tisto's original comment though. One reason he brings this up is if we want to change that PortalTransforms API in the future, then rewriting all these tests to comply to a new API would be a pain. There are 2 ways around this:

```
Split out code in convert() that purely deals with the transform into a separate function that takes in HTML (and options as a dict) and returns filtered HTML. Then test that your internal function works, and you have interfaced your internal function to the PortalTransforms API correctly separately.
Pull the common code out of each test in test_safe_html.py into a helper function, so you only have one bit of code
```

I suspect @tisto's approach would tend to the former, mine would tend to the latter. Either is fine.

However, this is drifting away from what this pull request is about. Feel free to copy/paste this discussion onto another pull request where this code is now.

**Comment by prakharjoshi** [comment]
@lentinj  I returned data._data for the convert() function as earlier test cases were not passing with only returning the data object so I returned the data value and also I think I have written wron test cases that is why they were failing as I was trying to check the input and output of html but I forgot that the cnvert function returns the data object and not the data value.. So the convert() function should return the data object as datastreaming , Am I right ?

**Comment by prakharjoshi** [comment]
@lentinj  @tisto  Okay.. So here is what I have understood so far.. We have created a new transform named "safe_html" and I have written a script to trim html using lxml and the output of out trasform will be datastream(into a file) and the input of out stream will also be datastream(from a file) and now when we talk about testing we will test the script by providing an input file and match it with the output file. The transform will take data in form of datastream and similarly it will output data the same way. So we have to create a input and output file for the test case and then test the transform against it. We will test mainly the convert() function where input will be from the input file and the output will be from the output file, right ?

**Comment by lentinj** [comment]
Hrm, that didn't go according to plan. I think what has happened is the controlpanel branch was a superset of this branch, so merging that also merged this, but then all also removed everything.

@prakharjoshi Can you recreate this pull request in a new branch from collective master? Checkout master, pull from the collective repository, then make a new branch. Then you can either try and revert commit `b0d1fc04c8`, or you can cheat and copy code out of the "files changed" tab on this page.

**Pull request merged**
