### PR TITLE
adding permission to the filter control panel

### PR DESCRIPTION
**Pull request by prakharjoshi**
I am trying to first fix the add-on set up so that we can access it from our site. Just added permissions right now now, working on it.

### CODE REVIEW

**Comment by prakharjoshi** [comment]
@lentinj  @tisto  I added the control pannel to the browser with permissions still on the site it is showing that the page is not avaliable... I added it as a page in the configuration.zcml in the browser module.. So need to configure something else to work that out ?

**Comment by tisto** [comment]
The name of the view registration (browser/configure.zcml) does not match the name of the control panel registration.

**Comment by prakharjoshi** [comment]
Okay I changed the name and unify the name everywhere, still when I hit the "HTML Filtering" option under Plone configuration on url "@@overview-controlpanel" it got stuck and in terminal "pdb" session starts saying "/home/prakhar/projects/experimental.safe_html_transform/eggs/plone.app.controlpanel-2.3.8-py2.7.egg/plone/app/controlpanel/filter.py(114)**init**()
-> getToolByName(context, 'portal_transforms'), 'safe_html')" . So I can't understand this log. And also after I exit the "pdb" mode here is what is shown under "@@filter-controlpanel" http://pastie.org/10251187

**Comment by tisto** [comment]
It seems you are trying to access the Plone filter control panel and not 
the one that you have registered.

Try to create a control panel by following this tutorial:

https://gist.github.com/tisto/4ef1f6c7b445faf6ad73

Am 21.06.15 um 08:32 schrieb prakhar:

**Comment by prakharjoshi** [comment]
Here I tried to correct the control panel according to tutorials and tried to run the url "http://localhost:8080/@@safe_html_transform-settings".. Still it is showing error http://pastebin.com/cCS7VS2B and I think the configuration.zcml under browser is fine. Please have a look at the code.

Do we need some type of views to show the control panel ? As I guess the url in the profile/controlpanel.xml is same as the name of the filter defined in the browser/configure.zcml. 

Also the classes imported in the filter configuration seems okay .

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  Here our control panel works perfectly on plone site. We can merge that request after travis's opinion ;)

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  We can merge this as this is all about installing control panel and there is nothing related to transform in it. Travis is also happy :)

**Comment by lentinj** [comment]
Looks good I think.

**Pull request merged**
