### PR TITLE
Installing Safe_Html transform

### PR DESCRIPTION
**Pull request by prakharjoshi**
This pull request will contain code to install the safe_html transform of experimental.safe_html_transform. only after proper installation we will be able to access the control panel.

### CODE REVIEW

**Comment by prakharjoshi** [comment]
@lentinj  @tisto  Here I tried to add the installTransform function in the setuphandler.py . Here When I do bin/instance fg and in the site setup when I install(activate) the experimental.safe_html_transform its working fine and here is the log for that http://pastebin.com/xucGUNar and when I tired to access the HTML filter on the site under plone configuration it shows error as shown http://pastebin.com/nTE4beLL . Please have a look at the last commit and guide me accordingly :)

**Comment by tisto** [comment]
@prakharjoshi would you mind adding a test that confirms that the new transform has been registered properly?

**Comment by lentinj** [comment]
Reading the documentation for setuphandlers will probably help: http://docs.plone.org/develop/addons/components/genericsetup.html#custom-installer-code-setuphandlers-py

**Comment by prakharjoshi** [comment]
Okay Will go through that :)

Prakhar Joshi
DA-IICT,Gandhinagar

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  I tried to update the safe_html transform with our new safe_html and put the code in setuphandler. But can't see travis link here. Tests are passing normally (I mean zope instance is working) . But still on HTML Filtering I get the same error :/

**Comment by lentinj** [comment]
Currently (d223526) setuphandlers.py is way overcomplicated. Can you clean it up please?

Also logging messages are good, but please use the standard python logging package for logging output, you already have an example of getting a logger object to use in previous code.

**Comment by lentinj** [comment]
Also, was ca42bee meant to be committed here, given it's a control panel thing? I'm guessing it should be reverted before it causes headaches with the other pull request.

**Comment by prakharjoshi** [comment]
@lentinj  Sure Will revert the last commit :)

**Comment by prakharjoshi** [comment]
@lentinj  So in setuphandler we install the safe_html transform similar to that done here https://github.com/tutor-web/tutorweb.content/blob/master/tutorweb/content/setuphandlers.py#L22 and not the way I did right now. I just tried to install the safe_html similar to the way we use to update the safe_html in the PortalTransfrom. So just need to confirm that ?

**Comment by lentinj** [comment]
I don't understand what you're asking. There isn't a dramatic functional difference between the 2 pieces of code, although the setuphandlers.py in this pull request has buckets of extra logic that isn't useful.

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  To register our safe_html we have to register mimetype ? As here are the log errors http://pastebin.com/SCkyyxEF and Here is the snippet of setuphandler http://pastebin.com/9UQj617r .

**Comment by lentinj** [comment]
The problem is in your transform, not the setuphandler.py. One of the following is true:-
- The input or output MIME types your transform uses are mis-spelt
- The input or output MIME types are missing
- The input or output MIME types aren't registered yet.

First, it's useful to know which of your MIME types aren't valid, so use `-D` when running your tests to get a PDB prompt, then use `u` to step up to around this point:-

```
  File "/home/prakhar/projects/experimental.safe_html_transform/eggs/Products.MimetypesRegistry-2.0.7-py2.7.egg/Products/MimetypesRegistry/MimeTypesRegistry.py", line 229, in lookup
    major, minor = split(str(mimetypestring))
   - __traceback_info__: ("'BROKEN'", 'BROKEN')
```

...and see what mimetypestring is. Your transform should only use core mimetypes from `Products.MimetypesRegistry` so there shouldn't be anything to register, more likely you need to declare dependencies in your genericsetup `metadata.xml` saying that use `Products.MimetypesRegistry` and `Products.PortalTransforms`.

**Comment by prakharjoshi** [comment]
@lentinj  @tisto  I did the pdb thing and tried to install the transforms seems like zope instance is working and tests are passing when running "bin/test -D --all". Have a look at the last commit. Don't know why travis is not working for this branch.. Working on it too

**Comment by prakharjoshi** [comment]
@lentinj  I think this setuphandler is correct, still there are issues with the mimetype, the mietype occuring there is "BROKEN" , I used the same mimetype as that of old safe_html so it should be registered already ?

**Comment by lentinj** [comment]
As I've said, if your mimetype in the module fails to be recognised, for one of the reasons above, then it returns BROKEN/BROKEN. You're right I think, the registration is fine and generally when installing into a Plone site all the MIME types you need are already there. However, this is when installing the transform during the tests, so the Plone site created for the tests will be very minimal. As a result, you may need to declare the dependencies as above (it may be something else wrong, but this is my best guess for now).

**Comment by prakharjoshi** [comment]
@lentinj  Sorry for late reply, so we should register the mimetype also in our add-on and then for test cases also that mimetype will not be new one, right ?

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  Can you please provide me the docs for how to use mimetype ? As I guess I am doing right with setuphandler, but just when I am adding my transform it is showing error so I guess I am doing wrong in using mimetype for safe_html. I have done this way for safe_html have a look http://pastebin.com/4dF8J9Py . Here the output type is x-html-safe and input is safe. I am little confussed in How to use mimetypes ? 

Also @lentinj  I tried to register the mimetype like this http://pastebin.com/naU2sRxa and used it in the setuphandler " registerMimeTypes(context, logger) " there. Still facing the same problem

**Comment by lentinj** [comment]
Again, your transform should only use core mimetypes from Products.MimetypesRegistry so there shouldn't be anything to register, more likely you need to declare dependencies in your genericsetup metadata.xml saying that you use Products.MimetypesRegistry and Products.PortalTransforms.

**Comment by prakharjoshi** [comment]
@lentinj  Okay So I added the dependencies in setup.py and also in profile/default/metadata.py . Metadata.py (<dependency>profile-Products.MimetypesRegistry:default</dependency>,<dependency>profile-Products.PortalTransforms:default</dependency>) and in setup.py I just added both products under install_require. When I ran the zope instance and on site setup it shows missing dependencies. Here is the error log while running test cases http://pastebin.com/9wfjEmh8

**Comment by prakharjoshi** [comment]
Okay So now dependencies problem is removed  but again there is error in mimetype as it is still broken. Working on it. Thanks @lentinj  for guiding me for installing dependencies, now working on correcting the mime type. :)

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  So here I found the flaw as we called pt.manage_addTransform(transforms, 'experimenatal.safe_html_transform.%s' % transforms) here https://github.com/prakharjoshi/experimental.safe_html_transform/commit/9412d561d4c0bf2386645922609712cc9c477b2b . So it calls the function here https://github.com/plone/Products.PortalTransforms/blob/master/Products/PortalTransforms/TransformEngine.py/#483 and in that function it calls _mapTransform here https://github.com/plone/Products.PortalTransforms/blob/master/Products/PortalTransforms/TransformEngine.py/#487 and the value of transform in that line is  "Transform at safe_html". But when I checked the value of transform in the _mapTransform function at https://github.com/plone/Products.PortalTransforms/blob/master/Products/PortalTransforms/TransformEngine.py/#249 its value is "Transform at st_to_html" . Any idea why this is happening as I think this is causing the break for Mimetype ?

**Comment by lentinj** [comment]
Enable logging output for your unit tests:-

http://docs.plone.org/manage/deploying/testing_tuning/testing_and_debugging/unit_testing.html#setting-log-level-in-unit-tests

You can run this code snippet in `setUpZope()` in `testing.py` so it is enabled for all unit tests. This should help clarify the problem.

**Comment by prakharjoshi** [comment]
@lentinj  Okay I activate the debugging and It shows that the deregistration is perfectly done but for registration it is not bale to find safe_html..(as far as I get from logs). Here are the logs http://pastebin.com/gFFiWN8A

**Comment by prakharjoshi** [comment]
@tisto  @lentinj . Here I changed our new transform name to exp_safe_html and then ran tests and they passes successfully. I think same name was creating problem. Have a look at that :)

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  I am still working to find out why travis failed but till now not able to find that so please have a look at that. Thanks in advance :)

**Comment by prakharjoshi** [comment]
@lentinj  @tisto  I am closing this also as it is also covered in #28

**Pull request closed without merging**
