### PR TITLE
trying not to break the lxml tree

### PR DESCRIPTION
**Pull request by prakharjoshi**
Here I tired not to break the tree and not render each node and rather I tried to just remove the additional <body> and <html> tags from the tree using regex. But it leads to failure for few test cases.

### CODE REVIEW

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  I tried the other way to clean html without breaking the lxml tree and got few tests which are getting failed. Have a look :)

**Comment by prakharjoshi** [comment]
Here I tried not to break the lxml tree structure, but it seems the "  " tags have been converted to "  " and when I tried to iterate over each node and then manipulate the nodes and then convert it into string again, then this problem was not there.

**Comment by lentinj** [comment]
Github's wiki markup ate your comments, but I can guess what you're saying, that it's converting `` in the tests into ``. Strictly speaking removing the `/` is correct, since `` is valid HTML. `` is XML.

I'm not sure if this would cause problems upstream, but I don't think this is bad. We are claiming the result is `text/html` after all, so having `` tags should be fine.

If you want to keep `` tags, https://bugs.launchpad.net/lxml/+bug/1353489 suggests that the way to do this would be to parse the document before filtering it.

**Comment by prakharjoshi** [comment]
Yeah. That will make things easy. Also is the tree structure now fine ? Also I tried to use the output same as this file https://github.com/plone/Products.PortalTransforms/blob/master/Products/PortalTransforms/tests/input/test_safehtml.html and the output I got is pretty well the tree structure, I have doubt about this tag " <![CDATA[Some CDATA text.]]> ". As what we are trying to pass here as lxml is removing that tag too.

**Comment by prakharjoshi** [comment]
Here tests will fail for extra whitespaces to the string. Working on it. Also corrected tests.

**Comment by prakharjoshi** [comment]
@lentinj here I didn't fragment the string and just directly removing body and other tags using regex, Is that a proper way ? Also there is always extra whitespace for the parsed string, can you guide me for removing that as that is the only test case that is failing here.

**Comment by lentinj** [comment]
You shouldn't really be using regular expressions for this at all.

If you give the cleaner a parsed tree (http://lxml.de/parsing.html#parsing-html) instead of a string then you get back a parsed tree instead of XML. Then you can do something like the following to get the contents of `<body>` as a string:-

http://stackoverflow.com/questions/4624062/get-all-text-inside-a-tag-in-lxml#answer-4624146

**Comment by prakharjoshi** [comment]
@lentinj  So the regular experession I am using for detecting tags so instead of that I should filter or change those tags inside the DOM tree only using etree.tags and something like that and then I should convert that tree into string as a output, right ? and I have seen the link also, will work on that :)

**Comment by prakharjoshi** [comment]
Another branch with same functionality got merged :D

**Pull request closed without merging**
