### PR TITLE
Issue#42

### PR DESCRIPTION
**Pull request by prakharjoshi**
Adding Read me for the add-on describing the add-on.

### CODE REVIEW

**Comment by gforcada** [comment]
Seems tests can not run due to an incompatible version pin, would you mind having a go at it?

**Comment by prakharjoshi** [comment]
@gforcada  I check that the plone.app.z3cform version pinned is 1.5.5 and as travis log says that it should be 0.7.7 and I tried to pin the `plone.app.z3cform` to 0.7.7 but while running buildout it is showing that 

```
While:
  Updating instance.
Error: Bad constraint 0.7.7 plone.app.z3cform>=1.1.0
```

So I guess I am interpreting the log error wrongly, is it so ?

**Comment by gforcada** [comment]
@prakharjoshi that's zc.buildout playing not nice with us. The error you pasted means "A PACKAGE I DO NOT TELL YOU has a dependency on plone.app.z3cform>=1.1.0 but you are forcing somewhere that package to version .0.7.7"

**Comment by gforcada** [comment]
A poor-man's way to solve this (i.e. what I usually do) is go to my home folder and inspect which package has this pin set, i.e.:

```
cd ~
cd .buildout/eggs
grep "plone.app.z3cform>=1.1.0" */EGG-INFO/requires.txt
```

That should print the list of packages that have this version pin set. Hopefully that helps :-)

**Comment by prakharjoshi** [comment]
@gforcada  So I got a list of three packages in the eggs folder and they are 

```
plone.app.contenttypes-1.2.4-py2.7.egg/EGG-INFO/requires.txt:plone.app.z3cform>=1.1.0.dev0
plone.app.dexterity-2.1.13-py2.7.egg/EGG-INFO/requires.txt:plone.app.z3cform>=1.1.0
plone.app.relationfield-1.3.2-py2.7.egg/EGG-INFO/requires.txt:plone.app.z3cform>=1.1.0.dev0
```

So now in my buildout I tried to pin them to lower version like this

```
plone.app.contenttypes = 1.2.2
plone.app.relationfield = 1.3.2
plone.app.dexerity = 2.1.11
```

But still travis is failing. Have I pinned these package to wrong version ?

**Comment by prakharjoshi** [comment]
Corrected in #45

**Comment by gforcada** [comment]
@prakharjoshi just to let you know: update your zc.buildout to 2.5.0 if there is any version conflict it should now be much more easier to know what's wrong, see http://reinout.vanrees.org/weblog/2015/11/16/buildout-nicer-version-conflicts.html

**Comment by prakharjoshi** [comment]
@gforcada I changes the buildouts from Plone-4 to Plone-5 so all the version conflicts have been removed, isn't that correct ? And yes this is also very useful :)

**Pull request closed without merging**
