### PR TITLE
Revert "#4 Control panel setup "

### PR DESCRIPTION
**Pull request by tisto**
Reverts collective/experimental.safe_html_transform#22

### CODE REVIEW

**Comment by tisto** [comment]
@lentinj @prakharjoshi we could revert my merge. Though, we would have to manually re-apply some commits as well I guess...

**Comment by prakharjoshi** [comment]
@lentinj @tisto Lets first finish with control pannel setup, will pick up transform setup later . I am working on configuration.zcml to make this work :)

**Comment by lentinj** [comment]
If there's a revert, then we still have to pick apart the controlpanel changes and the additional transform.

I think it'll be easier to leave the history as-is, and work on a separate pull request that adds the new transform and registers it.

**Comment by prakharjoshi** [comment]
Yeah I agree so on another pull request #25 I am working for control panel things and will register the safe_html transform by creating new pull request.

**Pull request closed without merging**
